name: Tests

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
  schedule:
  - cron: "0 2 * * 1-5"  # run on weekdays at 2:00am UTC

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python_version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Setup mamba
      uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: conda-forge

    - name: Create the conda environment
      shell: bash -l {0}
      run: mamba install -q python=${{ matrix.python_version }} pip jupyterlab_pygments==0.1.0 nbconvert=5.5 pytest-cov nodejs flake8 ipywidgets matplotlib xeus-cling

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        whereis python
        python --version
        python -m pip install "traitlets>=4,<5"

        python -m pip install ".[test]"
        cd tests/test_template; python -m pip install .; cd ../../;

    - name: Run tests
      shell: bash -l {0}
      run: |
        VOILA_TEST_DEBUG=1 VOILA_TEST_XEUS_CLING=1 py.test tests/ --async-test-timeout=240
        voila --help  # Making sure we can run `voila --help`

    - name: Flake8
      shell: bash -l {0}
      run: |
        python -m flake8 voila tests setup.py
